name: 'Matthew L Cox '
favicon: null
layout_spectrum: 0.98915
typography_spectrum: 0.9374489246401936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#5e4a3f'
    - '#ccb0ad'
    - '#a18280'
    - '#282320'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
