name: 'Matthew L Cox '
favicon: null
layout_spectrum: 0.98915
typography_spectrum: 0.1394
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#5e4a3f'
    - '#ccb0ad'
    - '#a18280'
    - '#282320'
  brandStrength: 0.5625
  lightness: 0.9375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
